### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by underthestars-zhy** [UWAppDev/SwiftUI-PhotoPicker#3]
If I add a lot of images at the same time. It will take a long time to `Importing Media`.

**Comment by ApolloZhu** [comment]
To provide a consistent API across all supported platforms, currently, this project has to import all the images to a temporary directory before returning (otherwise the URLs will expire). I'm mostly certain this process is already parallelized, but indeed it can be slow when there are a lot of things to import.

I believe the following approaches would allow the bulk importing process to be skipped, and I'll try to work on them in the next few days:

1. Exposing the underlying `[PHPickerResult]` on iOS for direct access (returns instantaneously)
2. Provide an `AsyncStream<Result<URL, Error>>` to allow handling each image separately as they load

**Comment by ApolloZhu** [comment]
Fixed in 0.0.2
